[build]
  publish = "."

# SPA fallback: serve index.html for all client-side routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# --- Examples for future advanced rules (left commented) ---
# [[redirects]]
#   from = "/old-path"
#   to = "/new-path"
#   status = 301
#   force = false
#   query = { path = ":path" }
#   conditions = { Language = ["en"], Country = ["US"], Role = ["admin"] }
#
# [[redirects]]
#   from = "/search"
#   to = "https://api.mysearch.com"
#   status = 200
#   force = true
#   headers = { X-From = "Netlify" }
#   signed = "API_SIGNATURE_TOKEN"
